/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author legen
 */
public class ReportFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReportFrame
     */
    public ReportFrame() {
        initComponents();
        
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        Date date = new Date();
        from_fdate.setText(sdf.format(date));
        to_fdate.setText(sdf.format(date));
        from_cdate.setText(sdf.format(date));
        to_cdate.setText(sdf.format(date));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cReport_panel = new javax.swing.JPanel();
        cto_label = new javax.swing.JLabel();
        cfrom_label = new javax.swing.JLabel();
        from_cdate = new javax.swing.JTextField();
        to_cdate = new javax.swing.JTextField();
        generate_creport = new javax.swing.JButton();
        donor_label = new javax.swing.JLabel();
        donors_list = new javax.swing.JComboBox<>();
        min_donation_label = new javax.swing.JLabel();
        min_donation = new javax.swing.JTextField();
        fReport_panel = new javax.swing.JPanel();
        ffrom_label = new javax.swing.JLabel();
        fto_label = new javax.swing.JLabel();
        from_fdate = new javax.swing.JTextField();
        to_fdate = new javax.swing.JTextField();
        generate_freport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1466, 754));

        cReport_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contributions Report"));

        cto_label.setText("To:");

        cfrom_label.setText("From:");

        generate_creport.setText("Generate Report(s)");

        donor_label.setText("Donor: ");

        donors_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        min_donation_label.setText("Min. Donation");

        javax.swing.GroupLayout cReport_panelLayout = new javax.swing.GroupLayout(cReport_panel);
        cReport_panel.setLayout(cReport_panelLayout);
        cReport_panelLayout.setHorizontalGroup(
            cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cReport_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cReport_panelLayout.createSequentialGroup()
                        .addComponent(generate_creport))
                    .addGroup(cReport_panelLayout.createSequentialGroup()
                        .addGroup(cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cReport_panelLayout.createSequentialGroup()
                                .addGroup(cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cReport_panelLayout.createSequentialGroup()
                                        .addComponent(donor_label)
                                        .addGap(18, 18, 18)
                                        .addComponent(donors_list, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cReport_panelLayout.createSequentialGroup()
                                        .addComponent(cfrom_label)
                                        .addGap(18, 18, 18)
                                        .addComponent(from_cdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cto_label)))
                                .addGap(18, 18, 18)
                                .addComponent(to_cdate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cReport_panelLayout.createSequentialGroup()
                                .addComponent(min_donation_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(min_donation, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        cReport_panelLayout.setVerticalGroup(
            cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cReport_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donor_label)
                    .addComponent(donors_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cfrom_label)
                    .addComponent(cto_label)
                    .addComponent(from_cdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_cdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min_donation_label)
                    .addComponent(min_donation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(generate_creport)
                .addContainerGap())
        );

        fReport_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Funds Report"));

        ffrom_label.setText("From:");

        fto_label.setText("To:");

        generate_freport.setText("Generate Report");

        javax.swing.GroupLayout fReport_panelLayout = new javax.swing.GroupLayout(fReport_panel);
        fReport_panel.setLayout(fReport_panelLayout);
        fReport_panelLayout.setHorizontalGroup(
            fReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fReport_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fReport_panelLayout.createSequentialGroup()
                        .addComponent(ffrom_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(from_fdate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(fto_label)
                        .addGap(18, 18, 18)
                        .addComponent(to_fdate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generate_freport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fReport_panelLayout.setVerticalGroup(
            fReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fReport_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fReport_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ffrom_label)
                    .addComponent(fto_label)
                    .addComponent(from_fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(generate_freport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fReport_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cReport_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(fReport_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(cReport_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cReport_panel;
    private javax.swing.JLabel cfrom_label;
    private javax.swing.JLabel cto_label;
    private javax.swing.JLabel donor_label;
    private javax.swing.JComboBox<String> donors_list;
    private javax.swing.JPanel fReport_panel;
    private javax.swing.JLabel ffrom_label;
    private javax.swing.JTextField from_cdate;
    private javax.swing.JTextField from_fdate;
    private javax.swing.JLabel fto_label;
    private javax.swing.JButton generate_creport;
    private javax.swing.JButton generate_freport;
    private javax.swing.JTextField min_donation;
    private javax.swing.JLabel min_donation_label;
    private javax.swing.JTextField to_cdate;
    private javax.swing.JTextField to_fdate;
    // End of variables declaration//GEN-END:variables
}
